version: "3.9"
services:
  api:
    build: .
    ports:
      - "9999:9999"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/docs"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    # Uncomment the following for live code reload in development
    # volumes:
    #   - ./app:/app/app
