version: "3.9"

services:
  surestrat-pineapple-api:
    build: .
    container_name: surestrat-pineapple-api
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped